In [1]:
import numpy as np

In [3]:

#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

arr = np.array([1,2,3,4,5])
print("Data type:")

print(arr.dtype)



Data type:
int64


In [2]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
print("Its Datatype is:")
print(arr.dtype)

Its Datatype is:
float64


In [13]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1 + 2j , 3 - 4j , 5 + 6j], dtype=np.complex128)
print(arr)
print(arr.dtype)

[1.+2.j 3.-4.j 5.+6.j]
complex128


In [15]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr= np.array([1,2,3,4,5,6],dtype=np.int32)

#convert to float
arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [16]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
# Creating a numpy array
arr = np.ones(4,dtype="float64")

# Display original array
print("Original Array:\n",arr,"\n")

# Display type of original array
print("type of Original Array:\n",arr.dtype,"\n")

# Converting array into float32
arr = np.float32(arr)

# Display type of modified array
print("type of modified array:\n",arr.dtype,"\n")

Original Array:
 [1. 1. 1. 1.] 

type of Original Array:
 float64 

type of modified array:
 float32 



In [17]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
arr = np.zeros((3,4))
print("arr:")
print(arr)
print("Shape of the array:",arr.shape)

print("Size of the array:",arr.size)

print("Type of the array:",(arr.dtype))

arr:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of the array: (3, 4)
Size of the array: 12
Type of the array: float64


In [22]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality
array_dimension = np.ones((3,4))
print("array_dimension")
print(array_dimension)

print("dimension")
print(array_dimension.ndim)

array_dimension
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
dimension
2


In [23]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
# create a numpy 2d-array
x = np.array([[100, 20, 34],
[300, 400, 600]])

print("Size of the array: ",
x.size)

print("Memory size of one array element in bytes: ",
x.itemsize)

# memory size of numpy array
print("Memory size of numpy array in bytes:",
	x.size * x.itemsize)

Size of the array:  6
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 48


In [26]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
array_strides = np.ones((10,10))

print("Array_strides:")
print(array_strides)

print("Array_strides:",array_strides.strides)

Array_strides:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Array_strides: (80, 8)


In [27]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

arr = np.array ([[1,2,3], [4,5,6]])

print("Array:")
print(arr)

print("Shape_stride_relationships:",arr)

print("Shape of the strides:",arr.shape)



Array:
[[1 2 3]
 [4 5 6]]
Shape_stride_relationships: [[1 2 3]
 [4 5 6]]
Shape of the strides: (2, 3)


In [28]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)
n_elements = 5
zeros_array = create_zeros_array(n_elements)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [30]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step.

arr = np.arange (1,10,0.1)

print("Generate_range_array:")
print(arr)

Generate_range_array:
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [36]:
#14  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

arr=(1.2,5.7,10)
print("Array")
print(arr)

print("Generate_linear_space:")
print(np.linspace(1.2,5.7))



Array
(1.2, 5.7, 10)
Generate_linear_space:
[1.2        1.29183673 1.38367347 1.4755102  1.56734694 1.65918367
 1.75102041 1.84285714 1.93469388 2.02653061 2.11836735 2.21020408
 2.30204082 2.39387755 2.48571429 2.57755102 2.66938776 2.76122449
 2.85306122 2.94489796 3.03673469 3.12857143 3.22040816 3.3122449
 3.40408163 3.49591837 3.5877551  3.67959184 3.77142857 3.86326531
 3.95510204 4.04693878 4.13877551 4.23061224 4.32244898 4.41428571
 4.50612245 4.59795918 4.68979592 4.78163265 4.87346939 4.96530612
 5.05714286 5.14897959 5.24081633 5.33265306 5.4244898  5.51632653
 5.60816327 5.7       ]


In [28]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

identity_matrix = np.eye(5)
print("Identity_matrix:")

print(identity_matrix)

Identity_matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
a = [1,2,3,"sushant",3+5j,True,2.55]
arr =np.array(a)

print("Array:")
print(arr)

Array:
['1' '2' '3' 'sushant' '(3+5j)' 'True' '2.55']


In [13]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

original_array = np.array([1, 2, 3, 4, 5])
print("Original array:")
print(original_array)
# Create a view with a different data type (int16)
view_array = original_array.view(dtype=np.int16)
print("\nView array with dtype=np.int16:")
print(view_array)



Original array:
[1 2 3 4 5]

View array with dtype=np.int16:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


CHECK 17 QUESTIONS


In [56]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Concatenate along axis 0 (vertically)
result = np.concatenate((array1, array2), axis=0)

print("Concatenated array:")
print(result)

Concatenated array:
[[1 2]
 [3 4]
 [5 6]]


In [57]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

# Create two sample arrays with different shapes
array1 = np.array([[1, 2], [3, 4]])  
array2 = np.array([5, 6])  

print("Array1:")
print(array1)

print("Array2:")
print(array2)

# Horizontally stack them
result = np.hstack((array1, array2[:, np.newaxis]))

print("Concatenated array:")
print(result)


Array1:
[[1 2]
 [3 4]]
Array2:
[5 6]
Concatenated array:
[[1 2 5]
 [3 4 6]]


In [30]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
stacked_result = np.vstack([arr1, arr2])
print("Array1:")
print(arr1)
print("Array2:")
print(arr2)
print("Stacked result:")
print(stacked_result)

Array1:
[[1 2]
 [3 4]]
Array2:
[[5 6]
 [7 8]]
Stacked result:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

# Creating an array of even integers from 30 to 70 (inclusive) with a step size of 2 using np.arange()
array = np.arange(30, 71, 2)

# Printing a message indicating an array of all the even integers from 30 to 70.
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [34]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

array1 = np.arange(0,1,0.1)
print("array1:")
print(array1)

array1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [35]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

# Generate 5 logarithmically spaced values between 1 and 1000
log_spaced_values = np.geomspace(1, 1000, num=5)

print(log_spaced_values)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [36]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
# importing pandas and numpy libraries
import numpy as np
import pandas as pd

data = np.random.randint(1, 100, size=(5, 3))
df = pd.DataFrame(data, columns=['Column_A',
                                 'Column_B',
                                 'Column_C'])

# displaying random integers in the dataframe
print(df)


   Column_A  Column_B  Column_C
0        16        88        40
1        88        94        87
2        31        91        82
3        25        57        95
4        26        80        90


In [38]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

df = pd.DataFrame({"A": [1, 2, -3, 4, -5, 6], 
                   "B": [3, -5, -6, 7, 3, -2], 
                   "C": [-4, 5, 6, -7, 5, 4], 
                   "D": [34, 5, 32, -3, -56, -54]}) 
  
# Displaying the original DataFrame 
print("Original Array :") 
print(df)

df[df < 0] = 0
print("New Array :") 
df

Original Array :
   A  B  C   D
0  1  3 -4  34
1  2 -5  5   5
2 -3 -6  6  32
3  4  7 -7  -3
4 -5  3  5 -56
5  6 -2  4 -54
New Array :


A  B  C   D
0  1  3  0  34
1  2  0  5   5
2  0  0  6  32
3  4  7  0   0
4  0  3  5   0
5  6  0  4   0

In [39]:
#26. Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

print("arr 3rd element:",arr[2])

arr 3rd element: 30


In [40]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("arr-2d index[1]:",arr_2d[1])

print("arr_2d index[2]:",arr_2d[2])

arr-2d index[1]: [4 5 6]
arr_2d index[2]: [7 8 9]


In [41]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])
boolean_indexing = arr[arr > 5]

print("boolean_indexing:",arr[arr>5])    


boolean_indexing: [ 8 10  7]


In [42]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Slice elements from 2 to index 5(inclusive)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])


[3 4 5 6]


In [52]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [55]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

a = np.array([[1,2,3],[4,5,6]])
print("a:")
print(a)

print("element in specific odrer:")
print([a[0:2, 1:2]])


a:
[[1 2 3]
 [4 5 6]]
element in specific odrer:
[array([[2],
       [5]])]


In [58]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_elements(arr, threshold):
    mask = arr > threshold
    return arr[mask]

arr = np.array([1, 2, 3, 4, 5])
threshold = 3
result = filter_elements(arr, threshold)
print(result)

[4 5]


In [59]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

a = np.random.randint(1,5,(3,3,3))
print("Array:")
print(a)
print("accessing element :" +str(a[0, 1, 0]))
print("accessing elements of a row and a column of an array:"
      +str(a[:, 1, 0]))
print("accessing sub part of an array :" +str(a[1]))

Array:
[[[3 4 2]
  [1 1 1]
  [2 4 4]]

 [[3 1 2]
  [2 3 1]
  [2 4 4]]

 [[3 2 2]
  [1 3 4]
  [4 2 3]]]
accessing element :1
accessing elements of a row and a column of an array:[1 2 1]
accessing sub part of an array :[[3 1 2]
 [2 3 1]
 [2 4 4]]


In [60]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# conditions
condition1 = arr > 3  # Elements greater than 3
condition2 = arr < 7  # Elements less than 7

# Combine conditions using logical AND
combined_condition = np.logical_and(condition1, condition2)

# Filter elements satisfying both conditions
result = arr[combined_condition]

print(result)



[4 5 6]


In [62]:
# 35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

a = [[1, 13, 6], [9, 4, 7], [19, 16, 2]]
arr = np.array(a)
print("Array:")
print(arr)

print(arr[0, :]),

print(arr[:, 2]),

print(arr[:,[0,1]])

Array:
[[ 1 13  6]
 [ 9  4  7]
 [19 16  2]]
[ 1 13  6]
[6 7 2]
[[ 1 13]
 [ 9  4]
 [19 16]]


In [64]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1,5,3],[6,4,3],[7,9,1]])
print("arr:")
print(arr)

# using broadcasting add 5 in arr.
print("New arr:")
print(arr+5)

arr:
[[1 5 3]
 [6 4 3]
 [7 9 1]]
New arr:
[[ 6 10  8]
 [11  9  8]
 [12 14  6]]


In [72]:
# 37  Consider two arrays arr1 of shape (1, 4) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])  

print("Array1:")
print(arr1)

print("Array2:")
print(arr2)

print("New array:")
print( arr1 * arr2)

Array1:
[[1 2 3 4]]
Array2:
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array:
[[ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]]


In [82]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1], [2], [3], [4]])

arr2 = np.array([[4, 6, 7], [8, 9, 10], [12, 13, 14],[11,19,33]])  
 
print("Array1:")
print(arr1)
print("Array2:")
print(arr2)
print("New_Array:")
print(arr1+arr2)

Array1:
[[1]
 [2]
 [3]
 [4]]
Array2:
[[ 4  6  7]
 [ 8  9 10]
 [12 13 14]
 [11 19 33]]
New_Array:
[[ 5  7  8]
 [10 11 12]
 [15 16 17]
 [15 23 37]]


In [83]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1], [2], [3]])  
arr2 = np.array([[10, 20, 30]])  

print("Array1:")
print(arr1)
print("Array2:")
print(arr2)

print("New array:")
print(arr1+arr2)

Array1:
[[1]
 [2]
 [3]]
Array2:
[[10 20 30]]
New array:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [4]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3], [4, 5, 6]])  
arr2 = np.array([[7, 8], [9, 10]])  

print("Array1:")
print(arr1)
print("Array2:")
print(arr2)

# Perform element-wise multiplication using broadcasting
#result = arr1[:, :, np.newaxis] * arr2
#print("Reshaped_arr2:\n",result)


# The resulting array will have shape (2, 3, 2)
#print(result)

Array1:
[[1 2 3]
 [4 5 6]]
Array2:
[[ 7  8]
 [ 9 10]]


Check Q40 in last.

In [9]:
#41. Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:")
print(arr)

print("Mean of array")
print(np.mean(arr))

Array:
[[1 2 3]
 [4 5 6]]
Mean of array
3.5


In [11]:
#42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
Maximum_value = [max(row) for row in arr]

Maximum_value

[3, 6]

In [6]:
#43. For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("arr:")
print(arr)

# Get the maximum value indices for each column
max_indices = np.argmax(arr, axis=0)

print("Indices of maximum values in each column:")
print(max_indices)

arr:
[[1 2 3]
 [4 5 6]]
Indices of maximum values in each column:
[1 1 1]


In [16]:
#45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

print("Array:")
print(arr)

print("All_even:")
#print(np.even(arr))
#check this

Array:
[[2 4 6]
 [3 5 7]]
All_even:


In [17]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3  # Set the desired dimensions (rows and columns)

reshaped_matrix = np.reshape(original_array, (m, n))
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [18]:
#47. Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [6]:
#48. Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print("Array1:")
print(array1)
print("Array2:")
print(array2)
print("concatenate array1&array2:")
print(np.concatenate((array1, array2), axis = 1) 
)

Array1:
[[1 2]
 [3 4]]
Array2:
[[5 6]
 [7 8]]
concatenate array1&array2:
[[1 2 5 6]
 [3 4 7 8]]


In [9]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original_array:")
print(original_array)

print("sub-array:")
print(np.array_split(original_array, 3, axis=0))

original_array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
sub-array:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [29]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert values at specified indices
    for idx, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, value)

    # Delete elements at specified indices
    original_array = np.delete(original_array, indices_to_delete)

    return original_array


original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Resulting array:", result_array)


Resulting array: [ 1 10 11  4  5]


In [31]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1,5,(3,4))
arr2 = np.random.randint(1,10,(3,4))
print("Array1:")
print(arr1)
print("Array2:")
print(arr2)
print("Element wise_addition:")
print(np.add(arr1,arr2))

Array1:
[[2 3 2 3]
 [3 2 3 1]
 [2 3 4 1]]
Array2:
[[7 7 3 7]
 [7 4 4 4]
 [5 2 7 8]]
Element wise_addition:
[[ 9 10  5 10]
 [10  6  7  5]
 [ 7  5 11  9]]


In [32]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
#from 1 to 10. Subtract `arr2` from `arr1` element-wise.

# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result (arr1 - arr2):", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result (arr1 - arr2): [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [33]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#Perform element-wise multiplication between `arr1` and `arr2`.

# Create arr1 with 5 random integers between 0 and 9
arr1 = np.random.randint(0, 10, 5)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result (arr1 * arr2):", result)


arr1: [3 5 4 9 6]
arr2: [1 2 3 4 5]
Result (arr1 * arr2): [ 3 10 12 36 30]


In [34]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
#    to 5. Perform element-wise division of `arr1` by `arr2`.

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result (arr1 / arr2):", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result (arr1 / arr2): [2. 2. 2. 2. 2.]


In [35]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#     reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Calculate element-wise exponentiation
result = arr1 ** arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result (arr1 ** arr2):", result)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result (arr1 ** arr2): [ 1 16 27 16  5]


In [36]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#    arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Create the array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Count occurrences of the substring 'hello'
substring = 'hello'
occurrences = np.char.count(arr, substring)

print("Occurrences of '{}':".format(substring), occurrences)


Occurrences of 'hello': [1 0 1 0 1]


In [37]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.

#   arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Convert strings to uppercase
uppercase_arr = np.char.upper(arr)

print("Original array:", arr)
print("Uppercase array:", uppercase_arr)


Original array: ['Hello' 'World' 'OpenAI' 'GPT']
Uppercase array: ['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [46]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#   arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

# Create the array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Replace occurrences of 'apple' with 'fruit'
new_arr = np.char.replace(arr, 'apple', 'fruit')

print("Original array:", arr)
print("Modified array:", new_arr)



Original array: ['apple' 'banana' 'grape' 'pineapple']
Modified array: ['fruit' 'banana' 'grape' 'pinefruit']


In [47]:
#59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate element-wise
concatenated_arr = np.core.defchararray.add(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Concatenated array:", concatenated_arr)

arr1: ['Hello' 'World']
arr2: ['Open' 'AI']
Concatenated array: ['HelloOpen' 'WorldAI']


In [49]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
longest_length = len(max(arr, key=len))

print("Length of the longest string:", longest_length)

Length of the longest string: 9


In [51]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
#  standard deviation of the dataset using NumPy's functions.

random_integers = np.random.randint(1, 1001, 100)


# Compute the mean, median, variance, and standard deviation
mean_value = np.mean(random_integers)
median_value = np.median(random_integers)
variance_value = np.var(random_integers)
std_deviation = np.std(random_integers)

print("Random integers:", random_integers)
print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation)


Random integers: [ 29 417 779 388 642 908 669 231 260 204 947 529 221 995 936 810 909 234
 447 992 713 242 703 635 358 122 551  25 249 388  49 209  46 654  13  37
 368 281 161 321 581 968 799 894 974 842 277 661 624 113  41 563 578 798
 459 899 428 337 626 713 220  24 770 246 692 613 485 329 508 908 149  52
 866 977  77 457 189 694 227 995 428 275 682 600 555 518 207 374 744  34
 198 666  30 136 337  91 911 651 162 315]
Mean: 472.39
Median: 452.0
Variance: 88993.2579
Standard Deviation: 298.3173778042439


In [61]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset

arr= np.random.randint(1, 101, 50)
print("Random_numbers:")
print(arr)

print("25th percentile of arr : ",
      np.percentile(arr, 25))

print("75th percentile of arr : ",
      np.percentile(arr, 75))

Random_numbers:
[ 2 45 49 49 47 81 41 50 36 24 40 94 27 66  9 77 77 87  3 92 44 43 60  2
 57 86 34 19 15 47 96 51  5 52 45 91 70 67 49 44 56 95 34 47 37 92 60  1
 54 75]
25th percentile of arr :  36.25
75th percentile of arr :  69.25


In [69]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

arr1 = np.random.rand(3, 3)
arr2 = np.random.rand(3, 3)
print("Array1:")
print("Array2:")
print(arr1),
print(arr2)
# Compute the correlation coefficient matrix
print("correlation_matrix:")
print(np.corrcoef(arr1, arr2))

Array1:
Array2:
[[0.20550276 0.05366035 0.75123424]
 [0.99118204 0.66140413 0.49140146]
 [0.11991553 0.84861301 0.91796396]]
[[0.91063121 0.3439409  0.96787887]
 [0.68062928 0.5967382  0.22165726]
 [0.54108582 0.67745145 0.65456288]]
correlation_matrix:
[[ 1.         -0.61012567  0.38356625  0.72782591 -0.9283149   0.15712148]
 [-0.61012567  1.         -0.96572755  0.09926711  0.86096357 -0.87832751]
 [ 0.38356625 -0.96572755  1.         -0.35414087 -0.69942781  0.97230916]
 [ 0.72782591  0.09926711 -0.35414087  1.         -0.42068885 -0.56288721]
 [-0.9283149   0.86096357 -0.69942781 -0.42068885  1.         -0.51303514]
 [ 0.15712148 -0.87832751  0.97230916 -0.56288721 -0.51303514  1.        ]]


In [70]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

matrix1 = np.random.rand(3, 4)
matrix2 = np.random.rand(4, 5)

# Compute the matrix product
result_matrix = np.dot(matrix1, matrix2)

print(result_matrix)


[[1.12729174 1.44804032 0.93398195 0.98342425 0.96725535]
 [0.24393412 0.4044954  0.34959909 0.16745004 0.31684055]
 [1.09753493 0.70686502 0.9962109  0.77956123 0.32592908]]


In [71]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles.

my_array = np.linspace(10, 1000, num=50, dtype=int)

# Calculate percentiles and quartiles
tenth_percentile = np.percentile(my_array, 10)
median = np.percentile(my_array, 50)
ninetieth_percentile = np.percentile(my_array, 90)
first_quartile = np.percentile(my_array, 25)
third_quartile = np.percentile(my_array, 75)

print(f"10th percentile: {tenth_percentile}")
print(f"Median (50th percentile): {median}")
print(f"90th percentile: {ninetieth_percentile}")
print(f"First quartile: {first_quartile}")
print(f"Third quartile: {third_quartile}")


10th percentile: 108.9
Median (50th percentile): 504.5
90th percentile: 900.1
First quartile: 257.0
Third quartile: 752.0


In [76]:
#66. Create a NumPy array of integers and find the index of a specific element.

# Create an array of integers from 1 to 50
my_array = np.arange(1, 51)

# Print the array
print(my_array)
# Let's say we want to find the index of the value 25
target_value = 25
index = np.where(my_array == target_value)[0]

# Print the index
print(f"Index of {target_value}: {index}")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Index of 25: [24]


In [81]:
#67. Generate a random NumPy array and sort it in ascending order.

my_array = np.random.randint(10, 1001, size=50)

# Sort the array in ascending order
sorted_array = np.sort(my_array)

# Print the sorted array
print(sorted_array)


[ 16  58  72  99 100 143 146 171 180 191 209 261 269 270 275 288 304 324
 334 381 384 426 465 501 510 564 577 582 613 619 651 690 721 725 791 798
 812 821 838 846 848 872 881 901 917 936 938 951 972 979]


In [82]:
#68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])
condition = arr > 20
# Apply the mask to filter the array
filtered_arr = arr[condition]

print("Original Array:", arr) 

print("Filtered Array:", filtered_arr)

Original Array: [12 25  6 42  8 30]
Filtered Array: [25 42 30]


In [83]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])

# Create a boolean mask for elements divisible by 3
mask = arr % 3 == 0

# Filter the array using the mask
filtered_arr = arr[mask]

print("Filtered array (divisible by 3):", filtered_arr)

Filtered array (divisible by 3): [12 15]


In [85]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array

arr = np.array([10, 20, 30, 40, 50])

filter_arr = arr >= 20
filter_arr1= arr <= 40

newarr = arr[filter_arr]
newarr1= arr[filter_arr1]
print(filter_arr)
print(filter_arr1)
print(newarr)
print(newarr1)

[False  True  True  True  True]
[ True  True  True  True False]
[20 30 40 50]
[10 20 30 40]


In [88]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder

arr = np.array([1, 2, 3])
# Get the byte order of the dtype
byte_order = arr.dtype.byteorder

print(f"Byte order of the array: {byte_order}")
print('Datatype:', arr.dtype)

Byte order of the array: =
Datatype: int64


In [89]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.


arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)  # Set to True for in-place swapping

print("Array after byte swapping:", arr)


Array after byte swapping: [16777216 33554432 50331648]


In [90]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

# Create a new array with swapped byte order
swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Swapped array:", swapped_arr)


Original array: [1 2 3]
Swapped array: [16777216 33554432 50331648]


In [91]:
#74

In [92]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

# Get the byte order of the dtype
byte_order = arr.dtype.byteorder

print(f"Byte order of the array: {byte_order}")


Byte order of the array: =


In [93]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
#an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11) 
copy_arr = np.copy(arr1)
copy_arr[5] = 99 
print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)

Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [ 1  2  3  4  5 99  7  8  9 10]


In [94]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
#the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

# Create a 2D array (matrix) of shape (3, 3) with random integers
matrix = np.random.randint(1, 101, size=(3, 3))

print("Original matrix:")
print(matrix)

view_slice = matrix[:2, :2]

print("View slice (2x2 submatrix):")
print(view_slice)

view_slice[1, 1] = 999

print("Modified view slice:")
print(view_slice)

print("Updated matrix after modifying view slice:")
print(matrix)


Original matrix:
[[ 7 60 13]
 [60 50 97]
 [79 40 18]]
View slice (2x2 submatrix):
[[ 7 60]
 [60 50]]
Modified view slice:
[[  7  60]
 [ 60 999]]
Updated matrix after modifying view slice:
[[  7  60  13]
 [ 60 999  97]
 [ 79  40  18]]


In [95]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

# Create a 1D array with integers from 1 to 12
array_a = np.arange(1, 13)

# Reshape it into a 2D array of shape (4, 3)
array_a = array_a.reshape(4, 3)

print("Original array_a:")
print(array_a)

view_b = array_a[:2, :2]

print("View slice (2x2 submatrix):")
print(view_b)

view_b += 5

print("Modified view_b after broadcasting:")
print(view_b)
print("Updated array_a after modifying view_b:")
print(array_a)


Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View slice (2x2 submatrix):
[[1 2]
 [4 5]]
Modified view_b after broadcasting:
[[ 6  7]
 [ 9 10]]
Updated array_a after modifying view_b:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)
print("orig_array:\n", orig_array)

reshaped_view = orig_array.reshape(4, 2)
print("reshaped_view:\n", reshaped_view)

reshaped_view[1, 0] = 99
print("Modified reshaped_view:\n", reshaped_view)

print("Modified orig_array:\n", orig_array)


orig_array:
 [[1 2 3 4]
 [5 6 7 8]]
reshaped_view:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modified reshaped_view:
 [[ 1  2]
 [99  4]
 [ 5  6]
 [ 7  8]]
Modified orig_array:
 [[ 1  2 99  4]
 [ 5  6  7  8]]


In [26]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
#elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(1,10,(3,4))
print("Data:\n", data)

Data:
 [[7 6 3 2]
 [8 1 6 7]
 [1 9 8 9]]


In [30]:
data_copy = (data[data>5])
data_copy

array([7, 6, 8, 6, 7, 9, 8, 9])

In [32]:
a = data_copy
a

array([7, 6, 8, 6, 7, 9, 8, 9])

In [33]:
a[0]=12
a

array([12,  6,  8,  6,  7,  9,  8,  9])

In [35]:
data_copy   # It affects the original data.

array([12,  6,  8,  6,  7,  9,  8,  9])

In [52]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.matrix([[2,4,8],[5,7,6],[3,8,9]])
B = np. matrix([[15,7,19],[4,12,18],[12,15,19]])
print("Matrix_A:\n",A)
print("Matrix_B:\n",B)
print("Addition of matrix A+B:\n",A+B)
print("Subtraction of matrix A-B:\n",A-B)

Matrix_A:
 [[2 4 8]
 [5 7 6]
 [3 8 9]]
Matrix_B:
 [[15  7 19]
 [ 4 12 18]
 [12 15 19]]
Addition of matrix A+B:
 [[17 11 27]
 [ 9 19 24]
 [15 23 28]]
Subtraction of matrix A-B:
 [[-13  -3 -11]
 [  1  -5 -12]
 [ -9  -7 -10]]


In [55]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

A = np.matrix([[2,4],[10,12],[5,7]])
print("Matrix_A:\n", A)
B = np.matrix([[11,3,15,5],[1,8,9,10]])
print("Matrix_B:\n", B)
C = A*B
print("Multiplication of A*B:\n", C)

Matrix_A:
 [[ 2  4]
 [10 12]
 [ 5  7]]
Matrix_B:
 [[11  3 15  5]
 [ 1  8  9 10]]
Multiplication of A*B:
 [[ 26  38  66  50]
 [122 126 258 170]
 [ 62  71 138  95]]


In [57]:
#83. Create a matrix `E` and find its transpose.
matrix_E= np.matrix([[1, 2, 3], [4, 5, 6]])

# Transposed matrix
transposed_matrix = matrix_E.transpose()
print(matrix_E)
print("\nTransposed Matrix:")
print(transposed_matrix)


[[1 2 3]
 [4 5 6]]

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [61]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.array([[2, 1, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the determinant
determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)
print("\nDeterminant of F:\n",determinant_F)

Matrix F:
[[2 1 3]
 [4 5 6]
 [7 8 9]]

Determinant of F:
 -9.000000000000005


In [62]:
# 85. Create a square matrix `G` and find its inverse.

G = np.array([[2, 1, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the inverse
inverse_G = np.linalg.inv(G)

print("Matrix G:")
print(G)
print("\nInverse of G:\n",inverse_G)

Matrix G:
[[2 1 3]
 [4 5 6]
 [7 8 9]]

Inverse of G:
 [[ 0.33333333 -1.66666667  1.        ]
 [-0.66666667  0.33333333 -0.        ]
 [ 0.33333333  1.         -0.66666667]]
